name: pa_sreens
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+12

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
# device_preview: ^1.2.0

  #-------test
#  better_player: ^0.0.84
#  flutter_vlc_player: ^7.4.3
#  video_player: ^2.9.5
#  shelf: ^1.4.2
#  shelf_static: ^1.1.3
  #=---------For ZoomIN
  photo_view: ^0.15.0
  gallery_saver_plus: ^3.2.9
  network_info_plus: ^7.0.0
  intl: ^0.20.2
  #-------others
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.1
  numberpicker: ^2.1.2
  image_gallery_saver_plus: ^4.0.1
  pinput: ^5.0.1
  sqflite: ^2.4.2
  gap: ^3.0.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter_xlider: ^3.5.0
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2
  cached_network_image: ^3.4.1
  csc_picker: ^0.2.7
  dio: ^5.8.0+1
  gal: ^2.3.2
  audioplayers: ^6.3.0
  torch_light: ^1.1.0
  scrollable_positioned_list: ^0.3.8
  animated_bottom_navigation_bar: ^1.4.0
  google_sign_in: ^6.1.5
  encrypt: ^5.0.3
  country_picker: ^2.0.27


  # -------------- Feezed
  # freezed_annotation: ^3.0.0
  # json_annotation: ^4.9.0
  flutter_svg: ^2.0.17
  # -------------- Permission
  permission_handler: ^11.4.0
  # -------------- Connectivity
  wifi_scan: ^0.4.1+2
  wifi_iot: ^0.3.19+2
  flutter_blue_plus: ^1.35.3
  flutter_libphonenumber: ^2.5.1
  syncfusion_flutter_datepicker: ^32.1.19
  syncfusion_flutter_core: ^32.1.19



  # -------------- Toast
  bot_toast: ^4.1.3
  toastification: ^3.0.1
  hydrated_bloc: ^10.0.0
  tutorial_coach_mark: ^1.2.13
  flutter_spinkit: ^5.2.1
  # network_info_plus: ^6.1.1

  # new features
  flutter_speed_dial: ^7.0.0
  native_opencv:
    path: native_opencv
  ffi: ^2.1.4
  path_provider: ^2.1.5
  keep_screen_on: ^5.0.0
  uuid: ^4.5.2
#  ffmpeg_kit_flutter_min_gpl: ^6.0.3
  ffmpeg_kit_min_gpl: ^6.0.3+2
#  json_serializable: ^6.9.4
  flutter_animate: ^4.5.2
  file_picker: ^9.0.2

  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  freezed_annotation: ^2.4.4
  freezed: ^2.5.7

  mime: ^2.0.0
  path: ^1.9.1
  http_parser: ^4.1.2
  url_launcher: ^6.3.1

  web_socket_channel: ^3.0.3
  device_info_plus: ^11.5.0
  geolocator: ^14.0.0
  connectivity_plus: ^6.1.5
  shimmer_animation: ^2.2.2
#  opencv_dart: ^1.4.3
#  flutter_local_notifications: ^19.4.0
  logger:
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  flutter_usb_camera:
    path: flutter_usb_camera

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^5.0.0
#  #-------------- Feezed Dev
#  freezed: ^3.0.3
#  flutter_gen_runner: ^5.10.0
#  build_runner: ^2.4.15
#  injectable_generator: ^2.7.0
  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.6.0
  # change_app_package_name: ^1.3.0
  injectable_generator: ^2.6.2



flutter:
  uses-material-design: true
  assets: 
    - assets/icons/
    - assets/images/
    - assets/database/
    - assets/audio/
    - assets/icons/bottom_navigation/
    - assets/icons/armory_icons/
    - assets/fonts/

  fonts:
    - family: "Regular"
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
    - family: "Bold"
      fonts:
        - asset: assets/fonts/Lato/Lato-Bold.ttf
    - family: "Helvetic"
      fonts:
        - asset: assets/fonts/Helvetic/helvetica-compressed.otf



flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
